# Generated by Django 4.0.6 on 2022-08-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.SmallIntegerField(blank=True, null=True)),
                ('altura', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
